### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by AlexAsh** [gshnlgnv/Testwork#1]
Не импортирован compose: https://github.com/gshnlgnv/Testwork/blob/7dfdfe382d9d98120f7504592b17bfd6eaaa203d/src/index.js#L9

**Comment by gshnlgnv** [comment]
Fixed in https://github.com/gshnlgnv/Testwork/commit/d532cef3173dd3ecfbf599aac8cedaac35194076
